let
    // Corte de 30 dias
    Hoje = Date.From(DateTime.LocalNow()),
    CutoffDate = Date.AddDays(Hoje, -30),

    // ================= DW (Histórico) =================

    Fonte = Odbc.DataSource("dsn=PostgreSQL30", [HierarchicalNavigation=true]),
    DW_DB = Fonte{[Name="dw_supplog",Kind="Database"]}[Data],
    DW_Schema = DW_DB{[Name="dw",Kind="Schema"]}[Data],
    TabelaDW = DW_Schema{[Name="tab_situacao_nota_logi",Kind="Table"]}[Data],

    DW_Tipos = Table.TransformColumnTypes(TabelaDW, {{"DAT_INCLUSAO", type date}}),
    DW_Historico = Table.SelectRows(DW_Tipos, each [DAT_INCLUSAO] < CutoffDate),

    // ================= ORIGEM (Últimos 30 dias) =================
    Origem_30D = Sql.Database("192.168.102.172", "LOGIXPRD", [
        Query = "
            SELECT *
            FROM dbo.VW_CONF_NOTAS
            WHERE EMISSAO >= DATEADD(DAY, -30, CONVERT(date, GETDATE()))
        "
    ]),
    Origem_Tipos = Table.TransformColumnTypes(Origem_30D, {{"EMISSAO", type date}}),
    Origem_Operacional = Table.SelectRows(Origem_Tipos, each [EMISSAO] >= CutoffDate),

    // ================= UNION =================
    BaseFinal = Table.Combine({DW_Historico, Origem_Operacional})

in
    BaseFinal