= Table.AddColumn(ColunasRemovidas, "ValidDia", each if [DATA] > Date.From(DateTime.LocalNow()) then 0 else 1)