Table.AddColumn(C, "PEDIDO_FIM", each Text.End(Text.From([STO], "pt-BR"), 
if Text.Length(Text.From([STO], "pt-BR")) = 11 then 1 else if
Text.Length(Text.From([STO], "pt-BR")) = 12 then 2 else if
Text.Length(Text.From([STO], "pt-BR")) = 13 then 3 else 0), type text)