let
    Fonte = Folder.Files("A:\UBERLÂNDIA\CD Souza Cruz\1 - PCP (SOUZA CRUZ)\Pedido Sherepoint\Cigarros\2024\12.DEZEMBRO.2024"),
    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Name] = "PROGRAMAÇÃO_DIARIA_01122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_02122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_03122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_04122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_05122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_06122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_07122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_08122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_09122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_10122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_11122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_12122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_13122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_14122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_15122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_16122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_17122024.xlsx" or [Name] = "PROGRAMAÇÃO_DIARIA_18122024.xlsx" or [Name] = "~$PROGRAMAÇÃO_DIARIA_06122024.xlsx")),
    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", Table.ColumnNames(#"Transformar Arquivo"(#"Arquivo de Amostra"))),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"Documento de compras", Int64.Type}, {"Data do documento", Int64.Type}, {"Material", Int64.Type}, {"Texto breve", type text}, {"Qtd,do pedido", type number}, {"Centro", type text}, {"Fornecedor/centro fornecedor", type text}, {"EMBARQUE", type text}, {"F.O", Int64.Type}, {"LOCALIDADE", type text}, {"PRIOR", Int64.Type}, {"TIPO", type text}, {"VOLCX", type number}, {"M³", type any}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"M³"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas",{{"VOLCX", Int64.Type}}),
    #"Intervalo de Texto Extraído" = Table.TransformColumns(#"Tipo Alterado1", {{"Nome da Origem", each Text.Middle(_, 19, 8), type text}}),
    #"Linhas Classificadas" = Table.Sort(#"Intervalo de Texto Extraído",{{"Nome da Origem", Order.Descending}}),
    #"Texto Substituído inserido" = Table.AddColumn(#"Linhas Classificadas", "DATA EMBARQUE", each Text.Replace([Nome da Origem], "12", "/12/"), type text),
    #"Valor Substituído" = Table.ReplaceValue(#"Texto Substituído inserido","/12//12/2024","12/12/2024",Replacer.ReplaceText,{"DATA EMBARQUE"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído",{{"DATA EMBARQUE", type date}}),
    #"Linhas Classificadas1" = Table.Sort(#"Tipo Alterado2",{{"DATA EMBARQUE", Order.Ascending}}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Linhas Classificadas1",{"DATA EMBARQUE", "Nome da Origem", "Documento de compras", "Data do documento", "Material", "Texto breve", "Qtd,do pedido", "Centro", "Fornecedor/centro fornecedor", "EMBARQUE", "F.O", "LOCALIDADE", "PRIOR", "TIPO", "VOLCX"}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas",{"Nome da Origem"}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Removidas1", each ([Documento de compras] <> null)),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas1",{{"Documento de compras", type text}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado3", {"Documento de compras"}, #"NFS CARREGADAS 02", {"STO"}, "NFS CARREGADAS 02", JoinKind.LeftOuter),
    #"NFS CARREGADAS 02 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "NFS CARREGADAS 02", {"Embarque (F.O)", "Data Embarque", "Tipo de Embarque", "NF/Série", "Classificação Produto"}, {"Embarque (F.O)", "Data Embarque.1", "Tipo de Embarque", "NF/Série", "Classificação Produto"}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"NFS CARREGADAS 02 Expandido",{"Data Embarque.1", "DATA EMBARQUE", "Documento de compras", "Data do documento", "Material", "Texto breve", "Qtd,do pedido", "Centro", "Fornecedor/centro fornecedor", "EMBARQUE", "F.O", "LOCALIDADE", "PRIOR", "TIPO", "VOLCX", "Embarque (F.O)", "Tipo de Embarque", "NF/Série", "Classificação Produto"}),
    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Reordenadas1"),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Duplicatas Removidas",{"Data Embarque.1", "DATA EMBARQUE", "Embarque (F.O)", "Documento de compras", "Data do documento", "Material", "Texto breve", "Qtd,do pedido", "Centro", "Fornecedor/centro fornecedor", "EMBARQUE", "F.O", "LOCALIDADE", "PRIOR", "TIPO", "VOLCX", "Tipo de Embarque", "NF/Série", "Classificação Produto"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas2",{"Data do documento"})
in
    #"Colunas Removidas2"