let
    Fonte = SharePoint.Tables("https://bat.sharepoint.com/sites/CuCoMerchan", [Implementation=null, ApiVersion=15]),
    #"5f914f8e-fc25-44d9-a05e-7e7257a48070" = Fonte{[Id="5f914f8e-fc25-44d9-a05e-7e7257a48070"]}[Items],
    #"Colunas Removidas" = Table.RemoveColumns(#"5f914f8e-fc25-44d9-a05e-7e7257a48070",{"FileSystemObjectType", "ContentTypeId", "Title", "OData__ColorTag", "ComplianceAssetId", "ServerRedirectedEmbedUri", "ServerRedirectedEmbedUrl"}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"Id", "Localidade", "SKU", "DescriçãodoSKU", "Desvio", "CategoriadoDesvio", "Desvio0", "VolumedoSKU", "Unidade", "ProcedênciadaReclama_x00e7", "PlacadaCarreta", "NotaFiscal", "DatadoRecebimento", "Observações", "StatusdaReclamação", "ClassificaçãodaOcorr", "ObservaçõesdoErro", "SetorResponsável", "FotosAberturaCuco", "CódigodeRastreabilidade", "StatusdaRastreabilidade", "ConformidadedaAbertura", "Datadaabertura", "Outro", "PaisdaReclamação", "DecisãoContestada", "Planta", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "ComentáriosAjusteFiscal", "DataeHoradaFabricaçã", "HoráriodarespostadoCUCO", "DatadoCarregamento", "SHIP", "ID", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas",{"CategoriadoDesvio"}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Removidas1",{"Id", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "ProcedênciadaReclama_x00e7", "PlacadaCarreta", "NotaFiscal", "DatadoRecebimento", "Observações", "StatusdaReclamação", "ClassificaçãodaOcorr", "ObservaçõesdoErro", "SetorResponsável", "FotosAberturaCuco", "CódigodeRastreabilidade", "StatusdaRastreabilidade", "ConformidadedaAbertura", "Datadaabertura", "Outro", "PaisdaReclamação", "DecisãoContestada", "Planta", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "ComentáriosAjusteFiscal", "DataeHoradaFabricaçã", "HoráriodarespostadoCUCO", "DatadoCarregamento", "SHIP", "ID", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Author", "Editor"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas1",{"PlacadaCarreta", "NotaFiscal", "ParentList", "Properties", "Versions", "Author", "Editor", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "AuthorId", "EditorId", "OData__UIVersionString", "ID", "Modified", "Created", "DataeHoradaFabricaçã", "HoráriodarespostadoCUCO", "DatadoCarregamento", "SHIP","ConformidadedaAbertura"}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Colunas Removidas2",{"Id", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "ProcedênciadaReclama_x00e7", "DatadoRecebimento", "Observações", "StatusdaReclamação", "ClassificaçãodaOcorr", "ObservaçõesdoErro", "SetorResponsável", "FotosAberturaCuco", "CódigodeRastreabilidade", "StatusdaRastreabilidade", "Outro", "PaisdaReclamação", "DecisãoContestada", "Planta", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal"}),
    #"Colunas Removidas3" = Table.RemoveColumns(#"Colunas Reordenadas2",{"Planta", "DecisãoContestada", "PaisdaReclamação", "Outro", "StatusdaRastreabilidade", "CódigodeRastreabilidade", "FotosAberturaCuco", "ProcedênciadaReclama_x00e7"}),
    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Colunas Removidas3",{"SetorResponsável", "Id", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "DatadoRecebimento", "Observações", "StatusdaReclamação", "ClassificaçãodaOcorr", "ObservaçõesdoErro", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal"}),
    #"Colunas Removidas4" = Table.RemoveColumns(#"Colunas Reordenadas3",{"ObservaçõesdoErro", "ClassificaçãodaOcorr"}),
    #"Colunas Reordenadas4" = Table.ReorderColumns(#"Colunas Removidas4",{"SetorResponsável", "Id", "DatadoRecebimento", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "Observações", "StatusdaReclamação", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Reordenadas4",{{"SetorResponsável", type text}, {"Id", Int64.Type}, {"DatadoRecebimento", type date}, {"Datadaabertura", type date}, {"Localidade", type text}, {"SKU", type text}, {"DescriçãodoSKU", type text}, {"VolumedoSKU", type number}, {"Unidade", type text}, {"Desvio", type text}, {"Desvio0", type text}, {"StatusAjusteFiscal", type text}, {"VolumeSobra", type number}, {"DescriçãodoSKUSobra", type text}, {"SKU-Sobra", type text}, {"StatusdaReclamação", type text}, {"Observações", type text}}),
    #"Colunas Reordenadas5" = Table.ReorderColumns(#"Tipo Alterado",{"SetorResponsável", "Id", "DatadoRecebimento", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "StatusdaReclamação", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "Observações"}),
    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Reordenadas5",null,"-",Replacer.ReplaceValue,{"SetorResponsável", "Localidade", "SKU", "DescriçãodoSKU", "Unidade", "Desvio", "Desvio0", "StatusdaReclamação", "DescriçãodoSKUSobra", "StatusAjusteFiscal", "Observações"}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",null,0,Replacer.ReplaceValue,{"Id", "VolumedoSKU", "SKU-Sobra", "VolumeSobra"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído1", each ([SetorResponsável] = "HUB")),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"SKU-Sobra", type text}}),
    #"Colunas Reordenadas6" = Table.ReorderColumns(#"Tipo Alterado1",{"Id", "SetorResponsável", "DatadoRecebimento", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "StatusdaReclamação", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "Observações"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Reordenadas6",{{"SKU", Int64.Type}}),
    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado2", "________________", each " "),
    #"Colunas Reordenadas7" = Table.ReorderColumns(#"Personalização Adicionada",{"Id", "________________", "SetorResponsável", "DatadoRecebimento", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "StatusdaReclamação", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "Observações"}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Reordenadas7",{{"________________", type text}}),
    #"Colunas Reordenadas8" = Table.ReorderColumns(#"Tipo Alterado3",{"________________", "Id", "SetorResponsável", "DatadoRecebimento", "Datadaabertura", "Localidade", "SKU", "DescriçãodoSKU", "VolumedoSKU", "Unidade", "Desvio", "Desvio0", "StatusdaReclamação", "SKU-Sobra", "DescriçãodoSKUSobra", "VolumeSobra", "StatusAjusteFiscal", "Observações"}),
    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Reordenadas8",{{"ComentáriosAjusteFiscal", type text}}),
    #"Valor Substituído2" = Table.ReplaceValue(#"Tipo Alterado4",null,"-",Replacer.ReplaceValue,{"ComentáriosAjusteFiscal"})
in
    #"Valor Substituído2"