let
    Fonte = 
    Table.SelectRows(
    Table.SelectRows(
    Sql.Database("192.168.102.154", "logixprd"),
    each ([Kind] = "View")){[Schema="totvssupp",Item="VW_TT_ESTOQUE"]}[Data],
    each ([COD_EMPRESA] = "04") and ([RAZ_SOCIAL] = "SOUZA CRUZ LTDA                                   ")),

    #"Texto Aparado" = Table.TransformColumns(Table.TransformColumnTypes(Fonte, {{"QTD_ORIGEM", type text},
     {"QTD_REGULARIZADA", type text}, 
     {"QTD_SALDO_FISICO", type text}, 
     {"QTD_RESERVA_NORMAL", type text}, 
     {"QTD_RESERVA_PROVIS", type text}, 
     {"QTD_SALDO_DISPONIVEL", type text}, 
     {"QTD_EM_TERCEIROS", type text}, 
     {"QTD_ITEM", type text}, 
     {"NUM_VOLUME", type text}, 
     {"DAT_HOR_PRODUCAO", type text}, 
     {"DAT_HOR_VALIDADE", type text}, 
     {"COMPRIMENTO", type text}, 
     {"LARGURA", type text}, 
     {"ALTURA", type text}, 
     {"DIAMETRO", type text}, 
     {"ROTATIVIDADE", type text}, 
     {"FUNCAO", type text}, 
     {"TIP_ESTRUTURA", type text}, 
     {"DAT_RECEBIMENTO", type text}, 
     {"PALETE_NIVEL", type text}, 
     {"PERC_VIDA_UTIL", type text}}, "pt-BR"),
     {{"COD_EMPRESA", Text.Trim, type text}, 
     {"COD_LOCAL", Text.Trim, type text}, 
     {"DES_LOCAL", Text.Trim, type text}, 
     {"AREA", Text.Trim, type text}, 
     {"DES_AREA", Text.Trim, type text}, 
     {"ENDERECO", Text.Trim, type text}, 
     {"DES_ENDERECO", Text.Trim, type text}, 
     {"DEPOSIT", Text.Trim, type text}, 
     {"RAZ_SOCIAL", Text.Trim, type text}, 
     {"ITEM", Text.Trim, type text}, 
     {"ITEM_DEPOSIT", Text.Trim, type text}, 
     {"DEN_ITEM", Text.Trim, type text}, 
     {"SKU", Text.Trim, type text}, 
     {"DES_SKU", Text.Trim, type text}, 
     {"IDENTIF_ESTOQUE", Text.Trim, type text}, 
     {"TIP_ESTOQUE", Text.Trim, type text}, 
     {"DES_TIP_ESTOQUE", Text.Trim, type text}, 
     {"RESTRICAO", Text.Trim, type text}, 
     {"DES_RESTRICAO", Text.Trim, type text}, 
     {"IES_SITUA_QTD", Text.Trim, type text}, 
     {"DEN_SITUA_QTD", Text.Trim, type text}, 
     {"QTD_ORIGEM", Text.Trim, type text}, 
     {"QTD_REGULARIZADA", Text.Trim, type text}, 
     {"QTD_SALDO_FISICO", Text.Trim, type text}, 
     {"QTD_RESERVA_NORMAL", Text.Trim, type text}, 
     {"QTD_RESERVA_PROVIS", Text.Trim, type text}, 
     {"QTD_SALDO_DISPONIVEL", Text.Trim, type text}, 
     {"QTD_EM_TERCEIROS", Text.Trim, type text}, 
     {"QTD_ITEM", Text.Trim, type text}, 
     {"PALETE", Text.Trim, type text}, 
     {"IDENTIF_SAIDA", Text.Trim, type text}, 
     {"IDENTIF_SAIDA_EXPED", Text.Trim, type text}, 
     {"RECEBIMENTO_INDUSTRIALIZACAO", Text.Trim, type text}, 
     {"ORIGEM_IDENTIF_ESTOQUE", Text.Trim, type text}, 
     {"CTR_ENT_SAI_VEIC_DOCUM", Text.Trim, type text}, {"NUM_LOTE", Text.Trim, type text},
     {"NUM_PECA", Text.Trim, type text}, {"NUM_SERIE", Text.Trim, type text}, 
     {"NUM_VOLUME", Text.Trim, type text}, {"DAT_HOR_PRODUCAO", Text.Trim, type text}, 
     {"DAT_HOR_VALIDADE", Text.Trim, type text}, {"COMPRIMENTO", Text.Trim, type text}, 
     {"LARGURA", Text.Trim, type text}, {"ALTURA", Text.Trim, type text}, 
     {"DIAMETRO", Text.Trim, type text}, {"ROTATIVIDADE", Text.Trim, type text}, 
     {"DES_ROTATIVIDADE", Text.Trim, type text}, {"FUNCAO", Text.Trim, type text}, 
     {"DES_FUNCAO", Text.Trim, type text}, {"TIP_ESTRUTURA", Text.Trim, type text}, 
     {"DES_TIP_ESTRUTURA", Text.Trim, type text}, {"CAT_ITEM", Text.Trim, type text}, 
     {"DES_CATEGORIA", Text.Trim, type text}, {"DAT_RECEBIMENTO", Text.Trim, type text}, 
     {"PALETE_NIVEL", Text.Trim, type text}, {"PALETE_EMPILHAMENTO", Text.Trim, type text}, 
     {"IDEN_ESTOQUE_AGRUPADA", Text.Trim, type text}, {"PERC_VIDA_UTIL", Text.Trim, type text}, 
     {"STATUS_VIDA_UTIL", Text.Trim, type text}}),
     
    #"Colunas Removidas" = Table.RemoveColumns(#"Texto Aparado",{"COD_EMPRESA", "COD_LOCAL", "DES_LOCAL", "AREA", "DES_AREA", "ENDERECO", "DEPOSIT", "RAZ_SOCIAL", "ITEM", "TIP_ESTOQUE", "RESTRICAO"}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"DES_RESTRICAO", "DES_TIP_ESTOQUE", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "DES_SKU", "IDENTIF_ESTOQUE", "IES_SITUA_QTD", "DEN_SITUA_QTD", "QTD_ORIGEM", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_EM_TERCEIROS", "QTD_ITEM", "PALETE", "IDENTIF_SAIDA", "IDENTIF_SAIDA_EXPED", "RECEBIMENTO_INDUSTRIALIZACAO", "ORIGEM_IDENTIF_ESTOQUE", "CTR_ENT_SAI_VEIC_DOCUM", "NUM_LOTE", "NUM_PECA", "NUM_SERIE", "NUM_VOLUME", "DAT_HOR_PRODUCAO", "DAT_HOR_VALIDADE", "COMPRIMENTO", "LARGURA", "ALTURA", "DIAMETRO", "ROTATIVIDADE", "DES_ROTATIVIDADE", "FUNCAO", "DES_FUNCAO", "TIP_ESTRUTURA", "DES_TIP_ESTRUTURA", "CAT_ITEM", "DES_CATEGORIA", "DAT_RECEBIMENTO", "PALETE_NIVEL", "PALETE_EMPILHAMENTO", "IDEN_ESTOQUE_AGRUPADA", "PERC_VIDA_UTIL", "STATUS_VIDA_UTIL"}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas",{"DES_SKU", "IES_SITUA_QTD", "DEN_SITUA_QTD", "IDENTIF_ESTOQUE"}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Removidas1",{"DES_RESTRICAO", "DES_TIP_ESTOQUE", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "QTD_ORIGEM", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_EM_TERCEIROS", "QTD_ITEM", "PALETE", "IDENTIF_SAIDA", "IDENTIF_SAIDA_EXPED", "RECEBIMENTO_INDUSTRIALIZACAO", "ORIGEM_IDENTIF_ESTOQUE", "CTR_ENT_SAI_VEIC_DOCUM", "NUM_LOTE", "NUM_PECA", "NUM_SERIE", "NUM_VOLUME", "DAT_HOR_PRODUCAO", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "COMPRIMENTO", "LARGURA", "ALTURA", "DIAMETRO", "ROTATIVIDADE", "DES_ROTATIVIDADE", "FUNCAO", "DES_FUNCAO", "TIP_ESTRUTURA", "DES_TIP_ESTRUTURA", "CAT_ITEM", "DES_CATEGORIA", "PALETE_NIVEL", "PALETE_EMPILHAMENTO", "IDEN_ESTOQUE_AGRUPADA", "PERC_VIDA_UTIL", "STATUS_VIDA_UTIL"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas1",{"NUM_SERIE", "NUM_VOLUME", "COMPRIMENTO", "LARGURA", "ALTURA", "DIAMETRO", "ROTATIVIDADE", "DES_ROTATIVIDADE", "FUNCAO", "TIP_ESTRUTURA", "DES_TIP_ESTRUTURA", "CAT_ITEM", "DES_CATEGORIA", "PALETE_NIVEL", "PALETE_EMPILHAMENTO", "PERC_VIDA_UTIL", "STATUS_VIDA_UTIL", "NUM_PECA", "RECEBIMENTO_INDUSTRIALIZACAO", "ORIGEM_IDENTIF_ESTOQUE", "IDENTIF_SAIDA", "IDENTIF_SAIDA_EXPED"}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Colunas Removidas2",{"DES_RESTRICAO", "DES_TIP_ESTOQUE", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "QTD_ORIGEM", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_EM_TERCEIROS", "QTD_ITEM", "PALETE", "CTR_ENT_SAI_VEIC_DOCUM", "NUM_LOTE", "DES_FUNCAO", "IDEN_ESTOQUE_AGRUPADA"}),
    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Colunas Reordenadas2",{"DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "QTD_ORIGEM", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_EM_TERCEIROS", "QTD_ITEM", "PALETE"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Reordenadas3",{{"ITEM_DEPOSIT", Int64.Type}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"ITEM_DEPOSIT"}, TB_BASE_ITENS, {"ITEM"}, "TB_BASE_ITENS", JoinKind.LeftOuter),
    #"TB_BASE_ITENS Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "TB_BASE_ITENS", {"EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "UNIDADE_MEDIDA"}, {"EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "UNIDADE_MEDIDA"}),
    #"Colunas Reordenadas4" = Table.ReorderColumns(#"TB_BASE_ITENS Expandido",{"EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA","DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "QTD_REGULARIZADA", "QTD_SALDO_FISICO","QTD_RESERVA_NORMAL","QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL"}),
    #"Colunas Removidas4" = Table.RemoveColumns(#"Colunas Reordenadas4",{"QTD_ITEM"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas4",{{"QTD_REGULARIZADA", type number}, {"QTD_SALDO_FISICO", type number}, {"QTD_RESERVA_NORMAL", type number}, {"QTD_RESERVA_PROVIS", type number}, {"QTD_SALDO_DISPONIVEL", type number}}),
    #"Colunas Removidas5" = Table.RemoveColumns(#"Tipo Alterado1",{"QTD_EM_TERCEIROS"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas5",{{"DAT_HOR_VALIDADE", type datetime}, {"DAT_RECEBIMENTO", type datetime}}),
    #"Data Extraída" = Table.TransformColumns(#"Tipo Alterado2",{{"DAT_HOR_VALIDADE", DateTime.Date, type date}, {"DAT_RECEBIMENTO", DateTime.Date, type date}}),
    #"Colunas Removidas6" = Table.RemoveColumns(#"Data Extraída",{"QTD_ORIGEM"}),
    #"Consultas Mescladas1" = Table.NestedJoin(#"Colunas Removidas6", {"DES_ENDERECO"}, #"CAPACIDADE DE ESTOQUE", {"ENDERECO_1"}, "CAPACIDADE DE ESTOQUE", JoinKind.LeftOuter),
    #"CAPACIDADE DE ESTOQUE Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "CAPACIDADE DE ESTOQUE", {"RUA", "COLUNA", "NIVEL", "TP_ESTOQUE", "CAT_POSICAO"}, {"RUA", "COLUNA", "NIVEL", "TP_ESTOQUE", "CAT_POSICAO"}),
    #"Colunas Reordenadas5" = Table.ReorderColumns(#"CAPACIDADE DE ESTOQUE Expandido",{"EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA","TP_ESTOQUE", "RUA", "COLUNA", "NIVEL", "CAT_POSICAO", "DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL"}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Reordenadas5",{{"COLUNA", Int64.Type}, {"RUA", type text}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado3",null,"-",Replacer.ReplaceValue,{"CTR_ENT_SAI_VEIC_DOCUM"}),
    #"Colunas Reordenadas6" = Table.ReorderColumns(#"Valor Substituído",{"DES_FUNCAO", "EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "TP_ESTOQUE", "RUA", "COLUNA", "NIVEL", "CAT_POSICAO", "DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "IDEN_ESTOQUE_AGRUPADA", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL"}),
    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Reordenadas6"),
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Duplicatas Removidas", "RESERVADO", each if [DES_RESTRICAO] = "SEM RESTRICAO" then [QTD_RESERVA_NORMAL] else 0),
    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"RESERVADO", type number}}),
    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Tipo Alterado4", "BLOQUEADO", each if [DES_RESTRICAO] <> "SEM RESTRICAO" then [QTD_RESERVA_NORMAL] else 0),
    #"Colunas Removidas3" = Table.RemoveColumns(#"Coluna Condicional Adicionada1",{"QTD_RESERVA_NORMAL"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas3",{{"RESERVADO", "QTD_RESERVA_NORMAL"}}),
    #"Colunas Reordenadas7" = Table.ReorderColumns(#"Colunas Renomeadas",{"DES_FUNCAO", "EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "TP_ESTOQUE", "RUA", "COLUNA", "NIVEL", "CAT_POSICAO", "DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "IDEN_ESTOQUE_AGRUPADA", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "BLOQUEADO"}),
    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Colunas Reordenadas7",{{"BLOQUEADO", type number}}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado5",{{"BLOQUEADO", "QTD_BLOQUEADO"}}),
    #"Colunas Reordenadas8" = Table.ReorderColumns(#"Colunas Renomeadas1",{"DES_FUNCAO", "EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "TP_ESTOQUE", "RUA", "COLUNA", "NIVEL", "CAT_POSICAO", "DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_HOR_PRODUCAO", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "IDEN_ESTOQUE_AGRUPADA", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_BLOQUEADO"}),
    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Colunas Reordenadas8",{{"DAT_HOR_PRODUCAO", type datetime}}),
    #"Data Extraída1" = Table.TransformColumns(#"Tipo Alterado6",{{"DAT_HOR_PRODUCAO", DateTime.Date, type date}}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Data Extraída1",null,"-",Replacer.ReplaceValue,{"NUM_LOTE"}),
    COL_SHLEF_LIFE_ADD = Table.AddColumn(#"Valor Substituído1", "SHELF_LIFE", each Duration.Days([DAT_HOR_VALIDADE]-DATA),Int64.Type),
    #"Colunas Reordenadas9" = Table.ReorderColumns(COL_SHLEF_LIFE_ADD,{"DES_FUNCAO", "EAN_REDUZ", "ITEM_REDZ", "CATEGORIA_ITEM", "SUB_CATEGORIA", "TP_ESTOQUE", "RUA", "COLUNA", "NIVEL", "CAT_POSICAO", "DES_TIP_ESTOQUE", "DES_RESTRICAO", "DES_ENDERECO", "SKU", "ITEM_DEPOSIT", "DEN_ITEM", "UNIDADE_MEDIDA", "DAT_HOR_PRODUCAO", "DAT_RECEBIMENTO", "DAT_HOR_VALIDADE", "SHELF_LIFE", "NUM_LOTE", "CTR_ENT_SAI_VEIC_DOCUM", "PALETE", "IDEN_ESTOQUE_AGRUPADA", "QTD_REGULARIZADA", "QTD_SALDO_FISICO", "QTD_RESERVA_NORMAL", "QTD_RESERVA_PROVIS", "QTD_SALDO_DISPONIVEL", "QTD_BLOQUEADO"}),
#"Consultas Mescladas2" = Table.NestedJoin(#"Colunas Reordenadas9", {"ITEM_DEPOSIT"}, TB_CONVERSAO, {"SKU"}, "TB_CONVERSAO", JoinKind.LeftOuter),
    #"TB_CONVERSAO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "TB_CONVERSAO", {"UNIDADE BASE NA CAIXA", "PACOTES/CARTELAS NA CAIXA", "UNIDADES NO PACOTE", "MENOR UNIDADE"}, {"UNIDADE BASE NA CAIXA", "PACOTES/CARTELAS NA CAIXA", "UNIDADES NO PACOTE", "MENOR UNIDADE"}),
    
    #"Personalização Adicionada" = Table.AddColumn(#"TB_CONVERSAO Expandido", "SALDO_REAL", each let
real = if [QTD_BLOQUEADO] = 0 then ([QTD_SALDO_FISICO]-[QTD_RESERVA_NORMAL]) else [QTD_BLOQUEADO]
in
real),
    Tipo_Alterado7 = Table.TransformColumnTypes(#"Personalização Adicionada",{{"SALDO_REAL", type number}})
   
in
    Tipo_Alterado7