"ENDERECO",
"DES_ENDERECO",
"DEPOSIT",
"RAZ_SOCIAL",
"ITEM",
"ITEM_DEPOSIT",
"SKU",
"DEN_ITEM",
"DES_SKU",
"IDENTIF_ESTOQUE",
"TIP_ESTOQUE",
"DES_TIP_ESTOQUE",
"RESTRICAO",
"DES_RESTRICAO",
"IES_SITUA_QTD",
"DEN_SITUA_QTD",
"QTD_ORIGEM",
"QTD_REGULARIZADA",
"QTD_SALDO_FISICO",
"QTD_RESERVA_NORMAL",
"QTD_RESERVA_PROVIS",
"QTD_SALDO_DISPONIVEL",
"QTD_EM_TERCEIROS",
"QTD_ITEM", "PALETE",
"IDENTIF_SAIDA",
"IDENTIF_SAIDA_EXPED",
"RECEBIMENTO_INDUSTRIALIZACAO",
"ORIGEM_IDENTIF_ESTOQUE",
"CTR_ENT_SAI_VEIC_DOCUM",
"NUM_LOTE",
"NUM_PECA",
"NUM_SERIE",
"NUM_VOLUME",
"DAT_HOR_PRODUCAO",
"DAT_HOR_VALIDADE",
"COMPRIMENTO",
"LARGURA",
"ALTURA",
"DIAMETRO",
"ROTATIVIDADE",
"DES_ROTATIVIDADE",
"FUNCAO",
"DES_FUNCAO",
"TIP_ESTRUTURA",
"DES_TIP_ESTRUTURA",
"CAT_ITEM", "DES_CATEGORIA",
"DAT_RECEBIMENTO",
"PALETE_NIVEL",
"PALETE_EMPILHAMENTO",
"IDEN_ESTOQUE_AGRUPADA",
"PERC_VIDA_UTIL",
"STATUS_VIDA_UTIL"




















_________________________-





"ENDERECO",
"DES_ENDERECO",
"DEPOSIT",
"RAZ_SOCIAL",
"ITEM",
"ITEM_DEPOSIT",
"SKU",
"DEN_ITEM",
"IDENTIF_ESTOQUE",
"DES_TIP_ESTOQUE",
"RESTRICAO",
"DES_RESTRICAO",
"IES_SITUA_QTD",
"DEN_SITUA_QTD",
"QTD_ORIGEM",
"QTD_REGULARIZADA",
"QTD_SALDO_FISICO",
"QTD_RESERVA_NORMAL",
"QTD_RESERVA_PROVIS",
"QTD_SALDO_DISPONIVEL",
"QTD_EM_TERCEIROS",
"QTD_ITEM",
"PALETE",
"IDENTIF_SAIDA",
"IDENTIF_SAIDA_EXPED",
"RECEBIMENTO_INDUSTRIALIZACAO",
"ORIGEM_IDENTIF_ESTOQUE",
"CTR_ENT_SAI_VEIC_DOCUM",
"NUM_LOTE",
"NUM_PECA",
"NUM_SERIE",
"NUM_VOLUME",
"DAT_HOR_PRODUCAO",
"DAT_HOR_VALIDADE",
"COMPRIMENTO",
"LARGURA",
"ALTURA",
"DIAMETRO",
"ROTATIVIDADE",
"DES_ROTATIVIDADE",
"FUNCAO",
"DES_FUNCAO",
"TIP_ESTRUTURA",
"DES_TIP_ESTRUTURA",
"CAT_ITEM",
"DAT_RECEBIMENTO",
"PALETE_NIVEL",
"PALETE_EMPILHAMENTO",
"IDEN_ESTOQUE_AGRUPADA",
"PERC_VIDA_UTIL",
"STATUS_VIDA_UTIL",







Table.TransformColumns( // RETIRA ESPAÇOS OCULTOS NOS TEXTOS DE TODAS AS COLUNAS
    Table.TransformColumnTypes( // ALTERA O TIPO DE DADOS, DE ACORDO COM TIPO DE CADA COLUNA
    Table.TransformColumns(SELECT_COLLS,{{"IDEN_ESTOQUE_AGRUPADA", Text.Trim, type text}}),
     {{"QTD_ORIGEM", type text}, {"QTD_REGULARIZADA", type text}, {"QTD_SALDO_FISICO", type text}, {"QTD_RESERVA_NORMAL", type text}, {"QTD_RESERVA_PROVIS", type text}, {"QTD_SALDO_DISPONIVEL", type text}, {"QTD_EM_TERCEIROS", type text}, {"QTD_ITEM", type text}, {"DAT_HOR_PRODUCAO", type text}, {"DAT_HOR_VALIDADE", type text}, {"FUNCAO", type text}, {"TIP_ESTRUTURA", type text}, {"DAT_RECEBIMENTO", type text}}, "pt-BR"),{{"DES_TIP_ESTOQUE", Text.Trim, type text}, {"ENDERECO", Text.Trim, type text}, {"DES_ENDERECO", Text.Trim, type text}, {"ITEM", Text.Trim, type text}, {"ITEM_DEPOSIT", Text.Trim, type text}, {"SKU", Text.Trim, type text}, {"DEN_ITEM", Text.Trim, type text}, {"IDENTIF_ESTOQUE", Text.Trim, type text}, {"RESTRICAO", Text.Trim, type text}, {"DES_RESTRICAO", Text.Trim, type text}, {"IES_SITUA_QTD", Text.Trim, type text}, {"DEN_SITUA_QTD", Text.Trim, type text}, {"QTD_ORIGEM", Text.Trim, type text}, {"QTD_REGULARIZADA", Text.Trim, type text}, {"QTD_SALDO_FISICO", Text.Trim, type text}, {"QTD_RESERVA_NORMAL", Text.Trim, type text}, {"QTD_RESERVA_PROVIS", Text.Trim, type text}, {"QTD_SALDO_DISPONIVEL", Text.Trim, type text}, {"QTD_EM_TERCEIROS", Text.Trim, type text}, {"QTD_ITEM", Text.Trim, type text}, {"PALETE", Text.Trim, type text}, {"ORIGEM_IDENTIF_ESTOQUE", Text.Trim, type text}, {"CTR_ENT_SAI_VEIC_DOCUM", Text.Trim, type text}, {"NUM_LOTE", Text.Trim, type text}, {"DAT_HOR_PRODUCAO", Text.Trim, type text}, {"DAT_HOR_VALIDADE", Text.Trim, type text}, {"FUNCAO", Text.Trim, type text}, {"DES_FUNCAO", Text.Trim, type text}, {"TIP_ESTRUTURA", Text.Trim, type text}, {"DES_TIP_ESTRUTURA", Text.Trim, type text}, {"CAT_ITEM", Text.Trim, type text}, {"DAT_RECEBIMENTO", Text.Trim, type text}, {"IDEN_ESTOQUE_AGRUPADA", Text.Trim, type text}})
