ConsultasMescladas1 = let
join = Table.NestedJoin(AlteraTiposdeDados, {"Material"}, TB_BASE_ITENS, {"ITEM"}, "TB_BASE_ITENS", JoinKind.LeftOuter),
expand = Table.ExpandTableColumn(join, "TB_BASE_ITENS", {"DESCRIÇÃO DO ITEM", "QTD_POR_CAIXA", "QTD_BASE_CX", "QTD_PACOTE_CX", "QTD_UN_PACOTE", "CATEGORIA_ITEM", "SUB_CATEGORIA", "MenorUnidadePCT", "DRIVE"}, {"DESCRIÇÃO DO ITEM", "QTD_POR_CAIXA", "QTD_BASE_CX", "QTD_PACOTE_CX", "QTD_UN_PACOTE", "CATEGORIA_ITEM", "SUB_CATEGORIA", "MenorUnidadePCT", "DRIVE"})
 //filtracigarro = Table.SelectRows(expand, each ([CATEGORIA_ITEM] = "CIGARRO"))
in
expand,
    
    // altera o tipo de dado da coluna MenorUnidadePCT, para tipo número
    AlteraTipo = Table.TransformColumnTypes(ConsultasMescladas1,
{{"MenorUnidadePCT",type number},{"DRIVE",type number},{"Material",type text}}),
    ColConversao = Table.AddColumn(AlteraTipo,"CONVERSAO",each ([Qtd.real em UGE]/[MenorUnidadePCT]), type number),
    
    // Cria a coluna Caixas
    ColCaixas = Table.AddColumn(ColConversao,
 "CAIXAS", each 
if [CATEGORIA_ITEM] =  "CIGARRO" then
Number.Round(Int64.From(Text.BeforeDelimiter(Text.From([CONVERSAO]/[QTD_BASE_CX]), ",")))
else 0

, type number),
    
    // Cria a coluna Pacotes
    ColPacotes = Table.AddColumn(ColCaixas, "PACOTES", each 
if [CATEGORIA_ITEM] =  "CIGARRO" then
Int64.From(Text.BeforeDelimiter(Text.From((([CONVERSAO]/[QTD_BASE_CX]) - [CAIXAS]) * [QTD_PACOTE_CX]), ","))
else 0, type number),
    // Cria a coluna Maços e Unidades
    ColMacos = Table.Buffer(
    Table.AddColumn(
        ColPacotes, 
        "MACOS_UN", 
        each 
            if [CATEGORIA_ITEM] = "CIGARRO" then
                let
                    // Calcula o valor decimal completo
                    valorCalculado = ((([CONVERSAO]/[QTD_BASE_CX]) - [CAIXAS]) * [QTD_PACOTE_CX] - [PACOTES]) * [QTD_UN_PACOTE],
                    
                    // Converte para texto e pega a parte antes da vírgula (caso exista)
                    parteInteira = Text.BeforeDelimiter(Text.From(valorCalculado, "pt-BR"), ",", {0, ""}),
                    
                    // Converte para número inteiro com tratamento de erro
                    resultado = try Number.From(parteInteira) otherwise 0
                in
                    resultado
            else
                0,
        type number
    )
),
    ColCaixasMilheiros = Table.AddColumn(ColMacos,"CAIXAS_MIL", 
each if [CATEGORIA_ITEM] = "CIGARRO" then ([CAIXAS]*10) else 0,
 type number),
    ColFracao = // se a categoria for  diferente de cigarro, trazer q quantidade real, senão trazer pacotes*0,2 + maços*0,02, resultando somente na fração
// se a categoria for  diferente de cigarro, trazer q quantidade real, senão trazer pacotes*0,2 + maços*0,02, resultando somente na fração
// se a categoria for  diferente de cigarro, trazer q quantidade real, senão trazer pacotes*0,2 + maços*0,02, resultando somente na fração
Table.AddColumn(ColCaixasMilheiros,"FRACAO_MIL",
each if  [CATEGORIA_ITEM] <> "CIGARRO" then // SE CATEGORIA FOR DIFERENTE DE CIGARRO TRAZ A QUANTIDADE ORIGINAL, SENÃO FAZ O CALCULO
[Qtd.real em UGE] 
else ([PACOTES]*0.2)+([MACOS_UN]*0.02), type number)