= Table.AddColumn(LinhasAgrupadas, "MÉDIA", each [QTD]/List.Sum(LinhasAgrupadas[QTD]),Percentage.Type)